import path from "path"
import os from "os"
import { lazy } from "../util/lazy"
import { Icon } from "./icon"

type Encoded = Record<string, { type: string; body: string; br?: string; gzip?: string }>

type Asset = {
  type: string
  body: Uint8Array<ArrayBuffer>
  br?: Uint8Array<ArrayBuffer>
  gzip?: Uint8Array<ArrayBuffer>
  etag: string
}

// The embedded bundle (produced by script/pack-web.ts from packages/app/dist)
// is what makes the binary self-contained. reload() overlays a fresh read of
// web-assets.json from disk onto the same Map, so a rebuilt UI goes live
// without restarting the process. Same serving path in both cases.
const decoded = new Map<string, Asset>()

function asset(
  type: string,
  body: Uint8Array<ArrayBuffer>,
  br?: Uint8Array<ArrayBuffer>,
  gzip?: Uint8Array<ArrayBuffer>,
) {
  // Hash the canonical (uncompressed) body so the validator is stable across
  // the br/gzip/identity variants of the same resource. Bun.hash is a fast
  // non-crypto hash; an ETag only needs to change when the bytes change.
  return { type, body, br, gzip, etag: `"${Bun.hash(body).toString(36)}"` }
}

// Each host labels its install icons with its hostname, so PWAs saved from
// different servers are told apart in the Dock. The manifest's
// icon URLs carry the icon's hash because Chrome refreshes an installed app's
// icon only when the URL changes, never for new bytes at the same URL
// (https://www.w3.org/2025/11/TPAC/demo-app-updating.html).
const branded = lazy(() => {
  const label = os.hostname().split(".")[0] ?? ""
  const manifest = decoded.get("/site.webmanifest")
  if (!label || !manifest) return new Map<string, Asset>()
  const icons = new Map(
    Object.entries(Icon.files).map(([name, size]) => [name, asset("image/png", Icon.png(size, label))]),
  )
  const parsed = JSON.parse(new TextDecoder().decode(manifest.body)) as { icons: { src: string }[] }
  const versioned = parsed.icons.map((icon) => {
    const generated = icons.get(icon.src)
    return generated ? { ...icon, src: `${icon.src}?v=${generated.etag.slice(1, -1)}` } : icon
  })
  const body = Buffer.from(JSON.stringify({ ...parsed, icons: versioned }))
  return new Map([...icons, ["/site.webmanifest", asset(manifest.type, body)]])
})

function fill(assets: Encoded) {
  decoded.clear()
  branded.reset()
  for (const [file, encoded] of Object.entries(assets)) {
    decoded.set(
      file,
      asset(
        encoded.type,
        Buffer.from(encoded.body, "base64"),
        encoded.br ? Buffer.from(encoded.br, "base64") : undefined,
        encoded.gzip ? Buffer.from(encoded.gzip, "base64") : undefined,
      ),
    )
  }
}

// Generated by script/pack-web.ts (gitignored), so a checkout that has not
// built the app typechecks, tests and runs from source without the web UI.
// @ts-ignore
const embedded: Encoded = await import("./web-assets.json", { with: { type: "json" } })
  .then((m) => m.default)
  .catch(() => ({}))
fill(embedded)

export namespace Web {
  export function available() {
    return decoded.size > 0 && decoded.has("/index.html")
  }

  export async function reload() {
    load((await Bun.file(path.resolve(import.meta.dir, "web-assets.json")).json()) as Encoded)
    return decoded.size
  }

  // Replaces the served bundle with an encoded asset map, the shape
  // script/pack-web.ts writes.
  export function load(assets: Encoded) {
    fill(assets)
  }

  // Serves the embedded SPA: exact asset by path, else index.html fallback so
  // client-side routes resolve. Returns null if no bundle is embedded. Serves the
  // brotli/gzip variant packed at build time when the client accepts it.
  export function serve(file: string, accept?: string, inm?: string): Response | null {
    const index = decoded.get("/index.html")
    if (!index) return null
    const exact = branded().get(file) ?? decoded.get(file === "/" ? "/index.html" : file)
    // A missing /assets/* is a real 404: those URLs are content-hashed, so an
    // absent one is a stale reference, not a client route. Serving index.html
    // there would hand back text/html under a .js/.css URL.
    if (!exact && file.startsWith("/assets/")) return new Response("not found", { status: 404 })
    const asset = exact ?? index
    // Vite content-hashes /assets/* filenames, so their bytes never change for a
    // given URL: cache them forever. Everything else (the index.html fallback)
    // revalidates so a rebuilt UI is picked up. The ETag lets that revalidation
    // return 304 instead of re-sending the whole shell when it hasn't changed.
    const hashed = asset !== index && file.startsWith("/assets/")
    if (inm === asset.etag)
      return new Response(null, {
        status: 304,
        headers: {
          ETag: asset.etag,
          "Cache-Control": hashed ? "public, max-age=31536000, immutable" : "no-cache",
        },
      })
    const encoding =
      asset.br && accept?.includes("br") ? "br" : asset.gzip && accept?.includes("gzip") ? "gzip" : undefined
    const body = encoding === "br" ? asset.br! : encoding === "gzip" ? asset.gzip! : asset.body
    const headers: Record<string, string> = {
      "Content-Type": asset.type,
      "Cache-Control": hashed ? "public, max-age=31536000, immutable" : "no-cache",
      ETag: asset.etag,
      Vary: "Accept-Encoding",
      // worker-src/script-src blob: for the dictation AudioWorklet, which loads
      // its module from an inline Blob URL. media-src blob: for synthesized
      // speech, which arrives as bytes and is played from an object URL.
      "Content-Security-Policy":
        "default-src 'self'; script-src 'self' 'wasm-unsafe-eval' blob:; worker-src 'self' blob:; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; media-src 'self' data: blob:; connect-src 'self' data:",
    }
    if (encoding) headers["Content-Encoding"] = encoding
    return new Response(body, { headers })
  }
}
